"""HTML dashboard reporter for GrooveGuard."""

from __future__ import annotations

from grooveguard.scanner import ScanResult


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GrooveGuard Security Report</title>
<style>
  :root {{
    --bg: #0f172a; --card: #1e293b; --text: #e2e8f0;
    --critical: #ef4444; --high: #f97316; --medium: #eab308;
    --low: #22c55e; --info: #3b82f6;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: var(--bg); color: var(--text); padding: 2rem; }}
  h1 {{ font-size: 1.8rem; margin-bottom: 0.5rem; }}
  .subtitle {{ color: #94a3b8; margin-bottom: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .stat-card {{ background: var(--card); border-radius: 12px; padding: 1.5rem; text-align: center; }}
  .stat-value {{ font-size: 2.5rem; font-weight: 700; }}
  .stat-label {{ color: #94a3b8; font-size: 0.875rem; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 0.25rem; }}
  .severity-critical {{ color: var(--critical); }}
  .severity-high {{ color: var(--high); }}
  .severity-medium {{ color: var(--medium); }}
  .severity-low {{ color: var(--low); }}
  .severity-info {{ color: var(--info); }}
  table {{ width: 100%; border-collapse: collapse; background: var(--card); border-radius: 12px; overflow: hidden; }}
  th, td {{ padding: 0.875rem 1rem; text-align: left; font-size: 0.875rem; }}
  th {{ background: #334155; font-weight: 600; text-transform: uppercase; font-size: 0.75rem; letter-spacing: 0.05em; }}
  tr {{ border-bottom: 1px solid #334155; }}
  tr:last-child {{ border-bottom: none; }}
  td {{ vertical-align: top; }}
  .badge {{ display: inline-block; padding: 0.25rem 0.5rem; border-radius: 6px; font-size: 0.75rem; font-weight: 600; text-transform: uppercase; }}
  .badge-critical {{ background: rgba(239,68,68,0.15); color: var(--critical); }}
  .badge-high {{ background: rgba(249,115,22,0.15); color: var(--high); }}
  .badge-medium {{ background: rgba(234,179,8,0.15); color: var(--medium); }}
  .badge-low {{ background: rgba(34,197,94,0.15); color: var(--low); }}
  .badge-info {{ background: rgba(59,130,246,0.15); color: var(--info); }}
  .rule-id {{ font-family: monospace; font-size: 0.8rem; color: #94a3b8; }}
  .file-path {{ font-family: monospace; font-size: 0.8rem; color: #60a5fa; }}
  .snippet {{ font-family: monospace; font-size: 0.8rem; background: #0f172a; padding: 0.5rem; border-radius: 6px; margin-top: 0.25rem; color: #cbd5e1; }}
  .remediation {{ color: #94a3b8; font-size: 0.8rem; margin-top: 0.25rem; }}
  .cwe {{ font-size: 0.75rem; color: #a78bfa; }}
  .footer {{ text-align: center; margin-top: 2rem; color: #64748b; font-size: 0.875rem; }}
</style>
</head>
<body>
<h1>🔒 GrooveGuard Security Report</h1>
<p class="subtitle">{files_scanned} files scanned in {duration:.2f} ms &nbsp;|&nbsp; Generated by GrooveGuard v1.0.0</p>

<div class="grid">
  <div class="stat-card">
    <div class="stat-value severity-critical">{critical}</div>
    <div class="stat-label">Critical</div>
  </div>
  <div class="stat-card">
    <div class="stat-value severity-high">{high}</div>
    <div class="stat-label">High</div>
  </div>
  <div class="stat-card">
    <div class="stat-value severity-medium">{medium}</div>
    <div class="stat-label">Medium</div>
  </div>
  <div class="stat-card">
    <div class="stat-value severity-low">{low}</div>
    <div class="stat-label">Low</div>
  </div>
  <div class="stat-card">
    <div class="stat-value severity-info">{info}</div>
    <div class="stat-label">Info</div>
  </div>
</div>

<table>
<thead>
<tr>
  <th>Severity</th>
  <th>Rule</th>
  <th>Location</th>
  <th>Message</th>
</tr>
</thead>
<tbody>
{rows}
</tbody>
</table>

<div class="footer">
  <p>🛡️ GrooveGuard Enterprise — <a href="https://github.com/GrooveXlabs/grooveguard" style="color:#60a5fa">github.com/GrooveXlabs/grooveguard</a></p>
</div>
</body>
</html>
"""

ROW_TEMPLATE = """<tr>
  <td><span class="badge badge-{severity_lower}">{severity}</span></td>
  <td>
    <div><strong>{title}</strong></div>
    <div class="rule-id">{rule_id}</div>
    {cwe_html}
  </td>
  <td>
    <div class="file-path">{file}</div>
    <div>Line {line}, Col {column}</div>
    {git_html}
  </td>
  <td>
    <div>{message}</div>
    {snippet_html}
    {remediation_html}
  </td>
</tr>
"""


class HTMLReporter:
    """Generate beautiful HTML security reports."""

    @staticmethod
    def generate(result: ScanResult) -> str:
        """Return an HTML string for the scan result."""
        counts = {"CRITICAL": 0, "HIGH": 0, "MEDIUM": 0, "LOW": 0, "INFO": 0}
        for f in result.findings:
            counts[f.severity] = counts.get(f.severity, 0) + 1

        rows = []
        for f in sorted(result.findings, key=lambda x: ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO").index(x.severity)):
            cwe_html = f"<div class='cwe'>{f.cwe_id}: {f.cwe_name}</div>" if f.cwe_id else ""
            git_html = f"<div style='font-size:0.75rem;color:#64748b'>👤 {f.git_author} · {f.git_date}</div>" if f.git_author else ""
            snippet_html = f"<div class='snippet'>{f.snippet}</div>" if f.snippet else ""
            remediation_html = f"<div class='remediation'>💡 {f.remediation}</div>" if f.remediation else ""
            rows.append(ROW_TEMPLATE.format(
                severity=f.severity,
                severity_lower=f.severity.lower(),
                title=f.title,
                rule_id=f.rule_id,
                cwe_html=cwe_html,
                file=f.file,
                line=f.line,
                column=f.column,
                git_html=git_html,
                message=f.message,
                snippet_html=snippet_html,
                remediation_html=remediation_html,
            ))

        return HTML_TEMPLATE.format(
            files_scanned=result.files_scanned,
            duration=result.duration_ms,
            critical=counts["CRITICAL"],
            high=counts["HIGH"],
            medium=counts["MEDIUM"],
            low=counts["LOW"],
            info=counts["INFO"],
            rows="\n".join(rows) if rows else '<tr><td colspan="4" style="text-align:center;padding:2rem">🎉 No findings detected!</td></tr>',
        )
